server-ip: "playsakura.online : 25627"
webhook: ""
username: "TheCodeBreaker"

onlinemessage:
  send: true
  avatarurl: "https://cdn1.iconfinder.com/data/icons/shop-payment-2/128/Shop-Payment-27-512.png"
  
offlinemessage:
  send: true
  avatarurl: "https://cdn1.iconfinder.com/data/icons/shopping-colored-icons-vol-1/128/P-1-82-128.png"
  
serverchat:
  send: true
  avatarurl: "https://cdn0.iconfinder.com/data/icons/line-color-mix-vol-3/128/office-73-128.png"

embed:
  online:
    title: "Server Status"
    field: "[Online]"
    value: "Server went live"
    color: 65280
  offline:
    title: "Server Status"
    field: "[Offline]"
    value: "Server went off"
    color: 16711680
  whitelist:
    enable:
      title: "SERVER STATUS"
      field: "WHITELIST"
      value: "Whitelist enable"
      color: 16776960
    disable:
      title: "SERVER STATUS"
      field: "WHITELIST"
      value: "Whitelist disable"
      color: 10026752
